services:
  - type: web
    name: bookmybox-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    autoDeploy: false

databases:
  - name: bookmybox-db
    databaseName: bookmybox
    user: bookmybox_user
