# data_for_boxes.py

box_data = [
    # Ahmedabad Locations
    {
        "name": "Super Sixes Cricket Arena",
        "sport": "Cricket",
        "sports": ["Cricket", "Football", "Badminton"],
        "location": "Thaltej, Ahmedabad",
        "price": 750.00,
        "rating": 4.7,
        "capacity": 12,
        "image": "box_images/super_sixes_cricket_arena.jpg",
        "images": [
            "box_images/super_sixes_cricket_arena_1.jpg",
            "box_images/super_sixes_cricket_arena_2.jpg",
            "box_images/super_sixes_cricket_arena_3.jpg",
        ],
        "amenities": ["Floodlights", "Changing Rooms", "Washrooms", "Cricket Nets", "Seating Area", "Parking"],
        "description": "Premium turf cricket arena with excellent lighting.",
        "full_description": "Experience cricket like never before at Super Sixes Cricket Arena. Our state-of-the-art turf pitches are perfect for both casual and competitive matches. Equipped with powerful floodlights, you can enjoy playing even after sunset. We provide clean changing rooms, modern washrooms, and dedicated cricket nets for practice. Ample parking is available for all visitors.",
        "rules": ["No spikes on turf", "Bookings are non-refundable 24 hours prior", "Outside food allowed (no alcohol)"],
        "latitude": 23.0560,
        "longitude": 72.5200,
    },
    {
        "name": "Ace Badminton Court",
        "sport": "Badminton",
        "sports": ["Badminton"],
        "location": "Satellite, Ahmedabad",
        "price": 300.00,
        "rating": 4.5,
        "capacity": 4,
        "image": "box_images/ace_badminton_court.jpg",
        "images": [],
        "amenities": ["Wooden Flooring", "AC", "Washrooms", "Water Cooler"],
        "description": "Indoor AC badminton court for comfortable play.",
        "full_description": "Ace Badminton Court offers a top-notch indoor badminton experience. Our courts feature professional wooden flooring and are fully air-conditioned, ensuring a comfortable playing environment year-round. Clean washrooms and a water cooler are available for your convenience.",
        "rules": ["Indoor shoes only", "No food inside court", "Minimum 1-hour booking"],
        "latitude": 23.0250,
        "longitude": 72.5100,
    },
    {
        "name": "The Football Turf, SG Highway",
        "sport": "Football",
        "sports": ["Football", "Futsal"],
        "location": "SG Highway, Ahmedabad",
        "price": 900.00,
        "rating": 4.8,
        "capacity": 10,
        "image": "box_images/football_turf_sg_highway.jpg",
        "images": [
            "box_images/football_turf_sg_highway_1.jpg",
            "box_images/football_turf_sg_highway_2.jpg",
        ],
        "amenities": ["FIFA Approved Turf", "LED Lighting", "Spectator Area", "Cafe", "First Aid"],
        "description": "High-quality football turf perfect for 5-a-side matches.",
        "full_description": "Our FIFA-approved football turf on SG Highway provides an unparalleled playing surface for 5-a-side and 7-a-side games. With powerful LED lighting, evening matches are a breeze. A dedicated spectator area, on-site cafe, and first-aid facilities ensure a complete and safe experience.",
        "rules": ["No metal studs", "Booking confirmed upon payment", "No smoking on premises"],
        "latitude": 23.0700,
        "longitude": 72.5050,
    },
    {
        "name": "Paddle Pro Ahmedabad",
        "sport": "Padel",
        "sports": ["Padel"],
        "location": "Science City Road, Ahmedabad",
        "price": 850.00,
        "rating": 4.6,
        "capacity": 4,
        "image": "box_images/paddle_pro_ahmedabad.jpg",
        "images": [],
        "amenities": ["Padel Rackets Rental", "Balls Provided", "Changing Rooms", "Parking"],
        "description": "Modern padel courts for enthusiasts and beginners.",
        "full_description": "Discover the fastest-growing racquet sport at Paddle Pro Ahmedabad. Our modern padel courts are designed for optimal play. We offer racket rentals and provide balls for your convenience. Clean changing rooms and ample parking are available.",
        "rules": ["Court shoes only", "Respect other players", "Booking required 1 hour in advance"],
        "latitude": 23.0800,
        "longitude": 72.5400,
    },
    {
        "name": "Ahmedabad Squash Arena",
        "sport": "Squash",
        "sports": ["Squash"],
        "location": "Bodakdev, Ahmedabad",
        "price": 400.00,
        "rating": 4.4,
        "capacity": 2,
        "image": "box_images/ahmedabad_squash_arena.jpg",
        "images": [],
        "amenities": ["Air-conditioned Court", "Pro Shop", "Locker Rooms"],
        "description": "Professional squash court with AC facility.",
        "full_description": "Hone your squash skills at Ahmedabad Squash Arena. Our air-conditioned court ensures a comfortable and intense game. A well-stocked pro shop offers equipment, and secure locker rooms are available.",
        "rules": ["Non-marking shoes", "Safety goggles recommended", "No food/drinks on court"],
        "latitude": 23.0500,
        "longitude": 72.5350,
    },
    {
        "name": "GTU Basketball Court",
        "sport": "Basketball",
        "sports": ["Basketball"],
        "location": "GTU Campus, Gandhinagar Rd, Ahmedabad",
        "price": 500.00,
        "rating": 4.3,
        "capacity": 10,
        "image": "box_images/gtu_basketball_court.jpg",
        "images": [],
        "amenities": ["Outdoor Court", "Seating", "Water Fountain"],
        "description": "Well-maintained outdoor basketball court for casual games.",
        "full_description": "Located within the GTU Campus, this outdoor basketball court is perfect for a friendly game or a serious practice session. It's well-maintained with clear markings and includes spectator seating and a water fountain.",
        "rules": ["No littering", "Share court space politely", "Bookings for exclusive use only"],
        "latitude": 23.1630,
        "longitude": 72.6369,
    },
    # All Over India Locations (Examples)
    {
        "name": "Powai Football Ground",
        "sport": "Football",
        "sports": ["Football", "Cricket", "Volleyball"],
        "location": "Powai, Mumbai",
        "price": 1200.00,
        "rating": 4.9,
        "capacity": 22,
        "image": "box_images/powai_football_ground.jpg",
        "images": [
            "box_images/powai_football_ground_1.jpg",
            "box_images/powai_football_ground_2.jpg",
        ],
        "amenities": ["Full-size Pitch", "Changing Rooms", "Showers", "Canteen", "Large Parking"],
        "description": "Expansive natural grass football ground for large matches.",
        "full_description": "The premier natural grass football ground in Powai, suitable for 11-a-side matches. Features include spacious changing rooms with hot showers, a fully stocked canteen, and ample parking for teams and spectators. Ideal for league matches and tournaments.",
        "rules": ["No smoking/alcohol", "Respect ground staff", "Bookings are final 48 hours prior"],
        "latitude": 19.1250,
        "longitude": 72.9080,
    },
    {
        "name": "Garden City Tennis Courts",
        "sport": "Tennis",
        "sports": ["Tennis"],
        "location": "Koramangala, Bengaluru",
        "price": 600.00,
        "rating": 4.6,
        "capacity": 4,
        "image": "box_images/garden_city_tennis.jpg",
        "images": [],
        "amenities": ["Clay Courts", "Coaching Available", "Equipment Rental", "Viewing Gallery"],
        "description": "Well-maintained clay tennis courts in the heart of Bengaluru.",
        "full_description": "Enjoy a game of tennis on our well-maintained clay courts in Koramangala. Coaching sessions are available for all skill levels, and you can rent equipment on-site. A comfortable viewing gallery is present for spectators.",
        "rules": ["Tennis attire required", "Bookings per hour", "Court etiquette must be followed"],
        "latitude": 12.9340,
        "longitude": 77.6100,
    },
    {
        "name": "Himalayan Rock Climbing Wall",
        "sport": "Climbing",
        "sports": ["Climbing"],
        "location": "DLF Phase 3, Gurugram",
        "price": 800.00,
        "rating": 4.7,
        "capacity": 8, # Per session
        "image": "box_images/himalayan_climbing_wall.jpg",
        "images": [
            "box_images/himalayan_climbing_wall_1.jpg",
            "box_images/himalayan_climbing_wall_2.jpg",
        ],
        "amenities": ["Auto-belays", "Bouldering Area", "Experienced Instructors", "Gear Rental"],
        "description": "Indoor rock climbing facility for all skill levels.",
        "full_description": "Scale new heights at Himalayan Rock Climbing Wall. Our indoor facility offers a variety of routes with auto-belay systems for beginners and a challenging bouldering area for experienced climbers. Our certified instructors are always on hand, and all necessary gear is available for rent.",
        "rules": ["Mandatory safety briefing", "Under 18s require guardian consent", "No loose clothing"],
        "latitude": 28.4700,
        "longitude": 77.0800,
    },
    {
        "name": "Chennai Beach Volleyball",
        "sport": "Volleyball",
        "sports": ["Volleyball", "Beach Volleyball"],
        "location": "ECR, Chennai",
        "price": 450.00,
        "rating": 4.2,
        "capacity": 10,
        "image": "box_images/chennai_beach_volleyball.jpg",
        "images": [],
        "amenities": ["Sand Court", "Nets Provided", "Changing Huts", "Refreshments Kiosk"],
        "description": "Authentic beach volleyball court near Chennai's ECR.",
        "full_description": "Enjoy the sun and sand with a game of beach volleyball on our authentic sand courts near Chennai's East Coast Road. Nets are provided, and basic changing huts and a refreshments kiosk are available for players.",
        "rules": ["No littering on beach", "Barefoot play encouraged", "Bookings for fixed slots"],
        "latitude": 12.9000,
        "longitude": 80.2500,
    },
    {
        "name": "Delhi Table Tennis Hub",
        "sport": "Table Tennis",
        "sports": ["Table Tennis"],
        "location": "Dwarka, New Delhi",
        "price": 250.00,
        "rating": 4.5,
        "capacity": 2,
        "image": "box_images/delhi_tt_hub.jpg",
        "images": [],
        "amenities": ["Professional Tables", "Robots for Practice", "Racket/Ball Rental"],
        "description": "Dedicated table tennis facility with professional equipment.",
        "full_description": "Delhi Table Tennis Hub offers a dedicated space for TT enthusiasts. We have professional tables, practice robots, and all necessary equipment available for rent. Ideal for both casual games and serious training.",
        "rules": ["Respect equipment", "Queue for tables during peak hours", "No food/drinks near tables"],
        "latitude": 28.6100,
        "longitude": 77.0300,
    },
    {
        "name": "Pune Skating Rink",
        "sport": "Skating",
        "sports": ["Skating", "Rollerblading"],
        "location": "Pimple Saudagar, Pune",
        "price": 350.00,
        "rating": 4.3,
        "capacity": 15,
        "image": "box_images/pune_skating_rink.jpg",
        "images": [],
        "amenities": ["Smooth Surface", "Skate Rental", "Instructor Available", "Music System"],
        "description": "Large indoor skating rink with smooth surface.",
        "full_description": "Glide smoothly at Pune Skating Rink. Our large indoor rink features a polished surface perfect for roller skating and rollerblading. Skates are available for rent, and instructors can provide guidance. Enjoy your session with our integrated music system.",
        "rules": ["Wear protective gear", "No rough play", "Follow rink directions"],
        "latitude": 18.6161,
        "longitude": 73.8055,
    },
    {
        "name": "Hyderabad Basketball Court",
        "sport": "Basketball",
        "sports": ["Basketball"],
        "location": "Gachibowli, Hyderabad",
        "price": 650.00,
        "rating": 4.6,
        "capacity": 10,
        "image": "box_images/hyderabad_basketball_court.jpg",
        "images": [],
        "amenities": ["Indoor Court", "Changing Rooms", "Air-conditioned", "Scoreboard"],
        "description": "State-of-the-art indoor basketball court.",
        "full_description": "Practice your hoops at our indoor basketball court in Gachibowli. Fully air-conditioned with professional flooring and a digital scoreboard, it's perfect for intense matches and training sessions. Clean changing rooms are available.",
        "rules": ["Non-marking shoes only", "No food/drinks on court", "Bookings required for exclusive use"],
        "latitude": 17.4470,
        "longitude": 78.3750,
    },
    {
        "name": "Super Sixes Cricket Arena",
        "sport": "Cricket",
        "sports": ["Cricket", "Football", "Badminton"],
        "location": "Thaltej, Ahmedabad",
        "price": 750.00,
        "rating": 4.7,
        "capacity": 12,
        "image": "box_images/super_sixes_cricket_arena.jpg",
        "images": [
            "box_images/super_sixes_cricket_arena_1.jpg",
            "box_images/super_sixes_cricket_arena_2.jpg",
            "box_images/super_sixes_cricket_arena_3.jpg",
        ],
        "amenities": ["Floodlights", "Changing Rooms", "Washrooms", "Cricket Nets", "Seating Area", "Parking"],
        "description": "Premium turf cricket arena with excellent lighting.",
        "full_description": "Experience cricket like never before at Super Sixes Cricket Arena. Our state-of-the-art turf pitches are perfect for both casual and competitive matches. Equipped with powerful floodlights, you can enjoy playing even after sunset. We provide clean changing rooms, modern washrooms, and dedicated cricket nets for practice. Ample parking is available for all visitors.",
        "rules": ["No spikes on turf", "Bookings are non-refundable 24 hours prior", "Outside food allowed (no alcohol)"],
        "latitude": 23.0560,
        "longitude": 72.5200,
    },
    {
        "name": "Ace Badminton Court",
        "sport": "Badminton",
        "sports": ["Badminton"],
        "location": "Satellite, Ahmedabad",
        "price": 300.00,
        "rating": 4.5,
        "capacity": 4,
        "image": "box_images/ace_badminton_court.jpg",
        "images": [],
        "amenities": ["Wooden Flooring", "AC", "Washrooms", "Water Cooler"],
        "description": "Indoor AC badminton court for comfortable play.",
        "full_description": "Ace Badminton Court offers a top-notch indoor badminton experience. Our courts feature professional wooden flooring and are fully air-conditioned, ensuring a comfortable playing environment year-round. Clean washrooms and a water cooler are available for your convenience.",
        "rules": ["Indoor shoes only", "No food inside court", "Minimum 1-hour booking"],
        "latitude": 23.0250,
        "longitude": 72.5100,
    },
    {
        "name": "The Football Turf, SG Highway",
        "sport": "Football",
        "sports": ["Football", "Futsal"],
        "location": "SG Highway, Ahmedabad",
        "price": 900.00,
        "rating": 4.8,
        "capacity": 10,
        "image": "box_images/football_turf_sg_highway.jpg",
        "images": [
            "box_images/football_turf_sg_highway_1.jpg",
            "box_images/football_turf_sg_highway_2.jpg",
        ],
        "amenities": ["FIFA Approved Turf", "LED Lighting", "Spectator Area", "Cafe", "First Aid"],
        "description": "High-quality football turf perfect for 5-a-side matches.",
        "full_description": "Our FIFA-approved football turf on SG Highway provides an unparalleled playing surface for 5-a-side and 7-a-side games. With powerful LED lighting, evening matches are a breeze. A dedicated spectator area, on-site cafe, and first-aid facilities ensure a complete and safe experience.",
        "rules": ["No metal studs", "Booking confirmed upon payment", "No smoking on premises"],
        "latitude": 23.0700,
        "longitude": 72.5050,
    },
    {
        "name": "Paddle Pro Ahmedabad",
        "sport": "Padel",
        "sports": ["Padel"],
        "location": "Science City Road, Ahmedabad",
        "price": 850.00,
        "rating": 4.6,
        "capacity": 4,
        "image": "box_images/paddle_pro_ahmedabad.jpg",
        "images": [],
        "amenities": ["Padel Rackets Rental", "Balls Provided", "Changing Rooms", "Parking"],
        "description": "Modern padel courts for enthusiasts and beginners.",
        "full_description": "Discover the fastest-growing racquet sport at Paddle Pro Ahmedabad. Our modern padel courts are designed for optimal play. We offer racket rentals and provide balls for your convenience. Clean changing rooms and ample parking are available.",
        "rules": ["Court shoes only", "Respect other players", "Booking required 1 hour in advance"],
        "latitude": 23.0800,
        "longitude": 72.5400,
    },
    {
        "name": "Ahmedabad Squash Arena",
        "sport": "Squash",
        "sports": ["Squash"],
        "location": "Bodakdev, Ahmedabad",
        "price": 400.00,
        "rating": 4.4,
        "capacity": 2,
        "image": "box_images/ahmedabad_squash_arena.jpg",
        "images": [],
        "amenities": ["Air-conditioned Court", "Pro Shop", "Locker Rooms"],
        "description": "Professional squash court with AC facility.",
        "full_description": "Hone your squash skills at Ahmedabad Squash Arena. Our air-conditioned court ensures a comfortable and intense game. A well-stocked pro shop offers equipment, and secure locker rooms are available.",
        "rules": ["Non-marking shoes", "Safety goggles recommended", "No food/drinks on court"],
        "latitude": 23.0500,
        "longitude": 72.5350,
    },
    {
        "name": "GTU Basketball Court",
        "sport": "Basketball",
        "sports": ["Basketball"],
        "location": "GTU Campus, Gandhinagar Rd, Ahmedabad",
        "price": 500.00,
        "rating": 4.3,
        "capacity": 10,
        "image": "box_images/gtu_basketball_court.jpg",
        "images": [],
        "amenities": ["Outdoor Court", "Seating", "Water Fountain"],
        "description": "Well-maintained outdoor basketball court for casual games.",
        "full_description": "Located within the GTU Campus, this outdoor basketball court is perfect for a friendly game or a serious practice session. It's well-maintained with clear markings and includes spectator seating and a water fountain.",
        "rules": ["No littering", "Share court space politely", "Bookings for exclusive use only"],
        "latitude": 23.1630,
        "longitude": 72.6369,
    },
    # More Ahmedabad Locations
    {
        "name": "Adani Arena Multisport",
        "sport": "Mixed Sports",
        "sports": ["Basketball", "Volleyball", "Badminton", "Table Tennis"],
        "location": "SG Road, Ahmedabad",
        "price": 1000.00,
        "rating": 4.8,
        "capacity": 15,
        "image": "box_images/adani_arena_multisport.jpg",
        "images": [
            "box_images/adani_arena_multisport_1.jpg",
            "box_images/adani_arena_multisport_2.jpg",
        ],
        "amenities": ["Indoor AC Stadium", "Multiple Courts", "Locker Rooms", "Shower Facilities", "Sports Shop"],
        "description": "A premier indoor facility for various sports with top-tier amenities.",
        "full_description": "Adani Arena Multisport boasts a sprawling indoor AC stadium designed to host a wide range of sports including basketball, volleyball, badminton, and table tennis. With multiple dedicated courts, professional lighting, spacious locker rooms, and hot shower facilities, it's the ultimate sporting destination. A well-stocked sports shop is also available on premises.",
        "rules": ["Appropriate sportswear required", "No food/drinks on courts", "Bookings must be prepaid"],
        "latitude": 23.0850,
        "longitude": 72.5150,
    },
    {
        "name": "Kankaria Lakeside Skating Rink",
        "sport": "Skating",
        "sports": ["Roller Skating", "Inline Skating"],
        "location": "Kankaria, Ahmedabad",
        "price": 200.00,
        "rating": 4.1,
        "capacity": 25,
        "image": "box_images/kankaria_skating_rink.jpg",
        "images": [],
        "amenities": ["Outdoor Rink", "Skate Rental", "First Aid Post", "Food Stalls Nearby"],
        "description": "Popular outdoor skating rink beside Kankaria Lake.",
        "full_description": "Enjoy outdoor skating at Kankaria Lakeside Skating Rink, a popular spot for roller and inline skating enthusiasts. The rink offers skate rentals and has a first-aid post for emergencies. Numerous food stalls are available nearby for refreshments.",
        "rules": ["Wear safety gear", "Skate in designated areas", "Children must be supervised"],
        "latitude": 23.0070,
        "longitude": 72.5970,
    },
    {
        "name": "Sabarmati Riverfront Cycle Track",
        "sport": "Cycling",
        "sports": ["Cycling"],
        "location": "Sabarmati Riverfront, Ahmedabad",
        "price": 150.00, # Price for cycle rental per hour
        "rating": 4.6,
        "capacity": 50, # Capacity for cycles available for rent
        "image": "box_images/sabarmati_cycle_track.jpg",
        "images": [],
        "amenities": ["Dedicated Cycle Track", "Cycle Rental", "Hydration Points", "Scenic Views"],
        "description": "Long, scenic cycle track along the Sabarmati Riverfront.",
        "full_description": "Explore Ahmedabad's beautiful Sabarmati Riverfront on two wheels! Our dedicated cycle track offers a smooth ride with breathtaking views. Cycles are available for rent at hourly rates, and hydration points are located along the route.",
        "rules": ["Stay on track", "Follow traffic rules", "Return cycles on time"],
        "latitude": 23.0290,
        "longitude": 72.5600,
    },
    # More All Over India Locations (Examples)
    {
        "name": "Salt Lake Futsal Courts",
        "sport": "Futsal",
        "sports": ["Futsal", "Football"],
        "location": "Salt Lake, Kolkata",
        "price": 800.00,
        "rating": 4.5,
        "capacity": 10,
        "image": "box_images/salt_lake_futsal.jpg",
        "images": [
            "box_images/salt_lake_futsal_1.jpg",
        ],
        "amenities": ["Indoor Turf", "Professional Goals", "Changing Rooms", "Water Bottle Refill"],
        "description": "State-of-the-art indoor futsal courts.",
        "full_description": "Our indoor futsal courts in Salt Lake are perfect for fast-paced 5-a-side games. Featuring high-quality turf and professional goals, they provide an excellent playing experience. Clean changing rooms and water refill stations are available.",
        "rules": ["Non-marking shoes only", "No food on turf", "Book in advance"],
        "latitude": 22.5700,
        "longitude": 88.4200,
    },
    {
        "name": "Goa Watersports Hub",
        "sport": "Watersports",
        "sports": ["Jet Skiing", "Parasailing", "Banana Boat Ride"],
        "location": "Baga Beach, Goa",
        "price": 1500.00, # Price per activity, e.g., per jet ski ride
        "rating": 4.9,
        "capacity": 1, # Per activity, per person
        "image": "box_images/goa_watersports.jpg",
        "images": [
            "box_images/goa_watersports_1.jpg",
            "box_images/goa_watersports_2.jpg",
        ],
        "amenities": ["Certified Instructors", "Life Jackets", "Safety Briefing", "Beachside Cafe"],
        "description": "Thrill-packed watersports adventures at Baga Beach.",
        "full_description": "Experience the excitement of jet skiing, parasailing, and banana boat rides at Goa Watersports Hub on Baga Beach. All activities are conducted with certified instructors and mandatory safety briefings. Life jackets are provided, and a lively beachside cafe keeps you refreshed.",
        "rules": ["Follow instructor guidelines", "No alcohol before activities", "Minimum age restrictions apply"],
        "latitude": 15.5560,
        "longitude": 73.7500,
    },
    {
        "name": "Jaipur Yoga Studio",
        "sport": "Yoga",
        "sports": ["Yoga", "Meditation", "Pilates"],
        "location": "C Scheme, Jaipur",
        "price": 350.00, # Price per session/class
        "rating": 4.7,
        "capacity": 20,
        "image": "box_images/jaipur_yoga_studio.jpg",
        "images": [],
        "amenities": ["AC Studio", "Yoga Mats Provided", "Changing Rooms", "Herbal Tea Bar"],
        "description": "Serene yoga studio offering various wellness classes.",
        "full_description": "Find your inner peace at Jaipur Yoga Studio. Our serene AC studio offers a variety of yoga, meditation, and pilates classes for all levels. Yoga mats are provided, along with comfortable changing rooms and a refreshing herbal tea bar.",
        "rules": ["Arrive 10 mins early", "Silence during class", "No phones in studio"],
        "latitude": 26.9000,
        "longitude": 75.8000,
    },
    {
        "name": "Lucknow Archery Range",
        "sport": "Archery",
        "sports": ["Archery"],
        "location": "Gomti Nagar, Lucknow",
        "price": 400.00, # Price per hour
        "rating": 4.4,
        "capacity": 5, # Max active shooters at one time
        "image": "box_images/lucknow_archery_range.jpg",
        "images": [],
        "amenities": ["Outdoor Range", "Equipment Rental", "Beginner Coaching", "Safety Gear"],
        "description": "Dedicated outdoor archery range for all skill levels.",
        "full_description": "Test your aim at Lucknow Archery Range. Our dedicated outdoor range provides a safe and fun environment for archery enthusiasts. Equipment rental is available, and beginner coaching ensures a great start. All necessary safety gear is provided.",
        "rules": ["Follow range officer instructions", "Never point bow at people", "Bookings required"],
        "latitude": 26.8700,
        "longitude": 81.0000,
    },
    {
        "name": "Bhopal Skating Park",
        "sport": "Skateboarding",
        "sports": ["Skateboarding", "BMX", "Rollerblading"],
        "location": "Arera Colony, Bhopal",
        "price": 180.00,
        "rating": 4.0,
        "capacity": 20,
        "image": "box_images/bhopal_skating_park.jpg",
        "images": [],
        "amenities": ["Skate Ramps", "Half-Pipes", "Seating Area", "Snack Kiosk"],
        "description": "Outdoor skate park with various ramps and obstacles.",
        "full_description": "Hit the ramps at Bhopal Skating Park! This outdoor park features a variety of skate ramps, half-pipes, and obstacles suitable for skateboarding, BMX, and rollerblading. A comfortable seating area and a snack kiosk are available for breaks.",
        "rules": ["Wear helmets", "Respect other riders", "No unauthorized modifications to ramps"],
        "latitude": 23.2300,
        "longitude": 77.4200,
    },
    {
        "name": "Indore Cricket Academy Nets",
        "sport": "Cricket",
        "sports": ["Cricket"],
        "location": "Vijay Nagar, Indore",
        "price": 600.00,
        "rating": 4.6,
        "capacity": 6, # Per net session
        "image": "box_images/indore_cricket_nets.jpg",
        "images": [],
        "amenities": ["Bowling Machines", "Coaching Available", "Turf Wickets", "Changing Rooms"],
        "description": "Professional cricket practice nets with advanced facilities.",
        "full_description": "Improve your batting and bowling at Indore Cricket Academy Nets. Our facility offers multiple turf wickets, bowling machines, and expert coaching sessions. Clean changing rooms are available for players.",
        "rules": ["Use appropriate gear", "No unauthorized personnel in nets", "Bookings per hour"],
        "latitude": 22.7500,
        "longitude": 75.8900,
    },
    {
        "name": "Chandigarh Cycling Track",
        "sport": "Cycling",
        "sports": ["Cycling"],
        "location": "Leisure Valley, Chandigarh",
        "price": 100.00, # Cycle rental
        "rating": 4.5,
        "capacity": 30, # Cycles available
        "image": "box_images/chandigarh_cycling_track.jpg",
        "images": [],
        "amenities": ["Well-maintained Track", "Cycle Rental", "Greenery", "Rest Benches"],
        "description": "Scenic cycling track through Chandigarh's green spaces.",
        "full_description": "Discover Chandigarh's beautiful Leisure Valley on our well-maintained cycling track. Enjoy the lush greenery and fresh air. Cycle rentals are available at various points, and rest benches are dotted along the track.",
        "rules": ["Stay on track", "No littering", "Share path with pedestrians respectfully"],
        "latitude": 30.7300,
        "longitude": 76.7800,
    },
]