# Generated by Django 5.2.4 on 2025-08-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0003_box_owner_box_rejection_reason_box_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark this box as featured to show it on the homepage.'),
        ),
    ]
