# Generated by Django 5.2.4 on 2025-08-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0004_box_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (e.g., Unsplash)', max_length=500, null=True),
        ),
    ]
