# Generated by Django 5.2.4 on 2025-08-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0001_initial'),
        ('user_profile', '0002_remove_userprofile_location_remove_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='achievements',
            field=models.ManyToManyField(blank=True, to='user_dashboard.achievement'),
        ),
    ]
