# Generated by Django 5.2.4 on 2025-08-15 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_userprofile_location_userprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
